# Generated by Django 2.2 on 2020-09-14 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tem_Post',
            new_name='TemPost',
        ),
    ]
